### ISSUE TITLE
Used in HomeAssistant Integration? MetaData Piping?

### ISSUE THREAD

**Issue by stephenmetzger** [uvjustin/pyforked-daapd#1]
Hey @uvjustin, not sure if this is the project used in the HA forked-daapd integration, but wanted to check to see if it was possible to get metadata into HA from your integration. I use forked-daapd along with shairport-sync for multi-room audio through AirPlay. I airplay from iOS to a shairport instance (shows up as airplay device called "Whole House") on the same machine as my forked-daapd server. I pipe the audio from "Whole House" into forked-daapd, which sends it to all the other airplay devices set up in forked-daapd. 

In HA, the forked-daapd media player entity works flawlessly, but shows the Artist/Track as "Unknown Artist/<Pipe Name>" and does not have album artwork. I've seen some threads with @mikebrady and @ejurgensen, discussing metadata pipes, but I'm not confident that its possible to pass metadata through shairport-->forked-daapd the way I'm using them together. Does this seem possible to you? Any suggestions?

**Comment by uvjustin** [comment]
Yes, this is the library used by the HA forked-daapd integration. It gets the metadata from the forked-daapd server.
I'm guessing that in your case the metadata is not reaching the forked-daapd server. If you go directly to the forked-daapd web interface, does the metadata show up?
If this is indeed the case, check that the metadata pipe is setup in your first shairport-sync instance (the one between your iOS and forked-daapd server) correctly. Make sure that the metadata section of your shairport-sync.conf file has the relevant fields uncommented. For forked-daapd to support metadata in a pipe, the name of the metadata pipe should be the name of the music pipe + ".metadata" (e.g. if your music pipe is "/path/to/pipe", the metadata pipe should be "/path/to/pipe.metadata"

**Comment by stephenmetzger** [comment]
Hey, thanks for the pointers @uvjustin. Appreciate the response, I'll dig a bit deeper.

**Comment by stephenmetzger** [comment]
Fantastic, got it working now. Had it set up correctly, but neglected to change permissions on the .metadata pipe. I ran cat /srv/music/<metadatapipe> and noticed nothing was loading, so assumed something was stopping metadata from by written. Thanks!

**Comment by uvjustin** [comment]
Great!

**Comment by stephenmetzger** [comment]
@uvjustin. And hey, thanks for putting this together. Was controlling forked-daapd using REST commands for on/off and volume sliders, but this is far more elegant and easier! Really appreciate your efforts.
