### ISSUE TITLE
TTS through forked-daapd media_player entity in HomeAssistant?

### ISSUE THREAD

**Issue by stephenmetzger** [uvjustin/pyforked-daapd#2]
The forked_daapd_server entity has a "text to speech" section within it's entity settings popup, but I cannot seem to get it to work either through the entity or by calling the tts.google_translate_say service to that entity. Is this something the forked-daapd integration is supposed to do? Do i have something misconfigured? Or, does the TTS mp3 that's generated have to somehow be sent to the pipe in the forked-daapd playlist?

Thanks again.

**Comment by uvjustin** [comment]
Yes, it works on my end, but haven't had a lot of feedback on it. Check that base_url is set in the TTS section as detailed here: https://community.home-assistant.io/t/no-tts-after-upgrade-to-110/198298/3
If that doesn't work, there might be some error messages in the logs which can help us figure out what's going on.
BTW, this repository is only for the backend library the HA integration uses. For questions or issues with the HA integration I think it's better to open topics at the forum https://community.home-assistant.io/ or specific bugs at https://github.com/home-assistant/core (it will still be me replying though :-))

**Comment by uvjustin** [comment]
@stephenmetzger Were you able to get this to work?

**Comment by stephenmetzger** [comment]
@uvjustin Thanks for following up on this. I haven't been able to get it to work, and it probably has something to do with how i have my HA instance configured (either with my proxy settings through NGINX or the way I have TTS set up in config). It creates a .mp3 file in my TTS folder, and seems like it trys to play (any audio currently playing is interupted and the media_player entity changes to look like it's trying to play the TTS), but no audio is produced.

**Comment by uvjustin** [comment]
Do you have any log events from HA or forked-daapd when you try to play TTS? 
Do you know if your TTS works with other integrations?
I found a post detailing a workaround for problems with TTS and NGINX with Sonos, but it doesn't seem like a forked-daapd build would be missing the cipher in question https://community.home-assistant.io/t/solution-sonos-tts-with-nginx-ssl-reverse-proxy/58136
