### ISSUE TITLE
TTS through forked-daapd plays on all speakers.

### ISSUE THREAD

**Issue by SalkinDK** [uvjustin/pyforked-daapd#3]
As stated in this [topic](https://community.home-assistant.io/t/forked-daapd-and-media-player-services/217126), when you send a TTS to the server entity it tries to play on all speakers instead of only the turned on ones.

**Comment by uvjustin** [comment]
This is an issue with the HA component and not with this library. I'm in the process of updating the component now, so we can discuss how to improve this functionality. Please post your suggestions on the HA forum topic you linked.
